version: '3'

services:
    test:
        image: freeipa:dc
        container_name: dc01
        volumes:
            - ./:/opt
            - /tmp/.X11-unix:/tmp/.X11-unix
        networks:
            - astra_net
        hostname: dc01.domain.test
        stdin_open: true
        tty: true
        ports:
            - '8000:5000'
        command: bash
        environment:
            - DISPLAY=$DISPLAY
        user: andrey

networks:
    astra_net:
        name: astra_net
        external: true
